# Links

**Palestras**

Julio Trecenti: 

- [Ferramental da ABJ](http://rpubs.com/julio_trecenti/ferramental).
- [Web Scraping](http://rpubs.com/julio_trecenti/scrape).
- [Administração do judiciário](http://rpubs.com/julio_trecenti/adm).

Fernando Correa: 

- [Análise de sobrevivência](https://github.com/abjur/curso/raw/master/pres/curso_tse.pdf).
- [Alocação de varas](https://github.com/abjur/alocTJSP).
- [Waze](https://github.com/abjur/tjsp_app).

Rafael Stern: 

- [Teoria da decisão](https://github.com/abjur/curso/raw/master/pres/presentation-teoria-decisao.pdf).
- [Weinstein](https://github.com/abjur/curso/raw/master/pres/presentation_guidelines.pdf).
- [Topic Models](https://github.com/abjur/curso/raw/master/pres/mining.pdf).

Carlos Alberto de Bragança Pereira: 

- [Inferência Bayesiana e estatística forense](https://github.com/abjur/curso/raw/master/pres/Aula_Brasilia.pdf). 
- [Livro de estatística forense](https://github.com/abjur/curso/raw/master/pres/BAYESIAN_SCIENCE_FORENSIC_W.pdf).

Julio Michael Stern: 

- [Intencionalidade vs Randomização](https://github.com/abjur/curso/raw/master/pres/ABJ161.pdf).

Adilson Simonis: 

- [Tópicos de probabilidade e estatística](https://github.com/abjur/curso/raw/master/pres/conference_presentation(6).pdf).

**Outros links**

- Github da ABJ: [https://github.com/abjur](https://github.com/abjur)
- Github do Julio: [https://github.com/jtrecenti](https://github.com/jtrecenti)
- Github do Fernando: [https://github.com/azeloc](https://github.com/azeloc)
- [Página do Rafael Stern](http://www.somos.ufscar.br/professores/view/3477)

`r if (knitr:::is_html_output()) '# Referências {-}' else '# Referências \nocite'`

Allen TT, Bernshteyn M (2008) Helping Franklin county vote in 2008: Waiting line report to
Michael Stinziano and Matthew Damschroder and The Franklin County Board of Elections
http://vote.franklincountyohio.gov/assets/pdf/press-releases/PR-07302008.pdf

 Karnon J, Stahl J, Brennan A, et al. Modeling using discrete
event simulation: a report of the ISPOR-SMDM Modeling Good
Research Practices Task Force—4. Med Decis Making. 2012;
32(5):701–11.

Dimitris Bertsimas and John N. Tsitsiklis (1997), Introduction to Linear Optimization,
Athena Scientific.

Alexey Izmailov and Mikhail Solodov (2007). Optimization, Volume 2: Computational Methods. 
Rio de Janeiro, Brazil. Second Edition
