--- 
title: "Curso de Jurimetria"
author: "Associação Brasileira de Jurimetria"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "Curso de Jurimetria dado ao TSE nos dias 08, 09 e 10 de agosto de 2016."
---

# Introdução

Essa é a primeira iteração do curso de Jurimetria da ABJ.
Nesse curso abordamos aspectos teóricos e práticos da Jurimetria,
essenciais para um profissional da Estatística que tenha interesse em
trabalhar nessa área de pesquisa.

O curso é voltado para estatísticos e está organizado em duas partes principais. 
Na primeira parte, 
apresentamos as ferramentas de trabalho do laboratório de Jurimetria,
que permitem a execução de nossas pesquisas.
Na segunda parte, apresentamos diversas aplicações da Jurimetria, 
focando em metodolodia de pesquisa, 
técnicas estatísticas e conceitos fundamentais de Jurimetria.

Para a primeira parte do curso, 
será necessário ter conhecimentos do software estatístico `R`,
como a lógica de programação, sintaxe do R e ambientação com o `RStudio`.
Para as partes seguintes, será necessário ter conhecimentos básicos
de estatística, como probabilidade, verossimilhança, inferência e
processos estocásticos.

